### ISSUE TITLE
Integration with Turbolinks causing redundant bootstraps

### ISSUE THREAD

**Issue by dsulli99** [philippd/angular-deferred-bootstrap#29] opened 2015-01-30 14:32 UTC
Hi,

I have a question (presumably an issue) regarding the use of deferred bootstrapper.  First and foremost, I'd like to say that I have it 'working'.  My problem is that I am using bootstrap in conjunction with Turbolinks (Rails 4).  The initial bootstrap (non deferred) code I used was this.  I could load the page as many times as I want without error.

$(document).on('ready page:load', function() {
    $(".swag.angularswag").each (function() {
        angular.bootstrap(document.body, ['ngCart'])
    }
}

Now, my code looks like this:

$(document).on('ready page:load', function() {
     $(".swag.angularswag").each (function() {
        deferredBootstrapper.bootstrap({
          element: document.body,
          module: 'ngCart',
          resolve: {
            APP_CONFIG: ['$http', function ($http) {
              return $http.get('/swag/listproducts.json');
           }]
         } 
 }

My problem is that if I revisit page with the $(".swag.angularswag") selector defined (after the initial load takes place), I receive the error:

Error: [ng:btstrpd] App Already Bootstrapped with this Element '<body class="swag angularswag ng-scope">'

If I use the code block at the top, it works fine (this error is never presented).  Is there a way that I can have this work in conjunction with Turbolinks?  I appreciate your help.

Dan

**Comment by philippd** [comment] 2015-02-01 00:18
Hi Dan

I don't know anything about Turbolinks, but it looks like the selector ```$(".swag.angularswag")``` might return multiple elements and therefore you'll try to bootstrap the same app multiple times on the ```body``` element. AngularJS does not allow this.

Is it possible that your intention is to bootstrap the ```ngCart``` app on each of the angularswag elements?

```javascript
 $(".swag.angularswag").each (function(swagElement) {
	deferredBootstrapper.bootstrap({
	element: swagElement,
	module: 'ngCart',
	resolve: {
		APP_CONFIG: ['$http', function ($http) {
			return $http.get('/swag/listproducts.json');
		}]
}
```

**Comment by dsulli99** [comment] 2015-02-05 13:31
Hi,

Thank you for your reply.  I understand what you are saying about the selector having more than one element but that is not actually the issue.  If you look at the code I provided I actually use the same selector to use the regular bootstrap and it works fine.  Anyway, I found a workaround to this (I used the self-executing anonymous function here: http://stackoverflow.com/questions/16286605/initialize-angularjs-service-with-asynchronous-data).  You can close this issue as far as I am concerned (it might be a bug however I am not concerned about it).  Thank you again for your help.

**Comment by philippd** [comment] 2015-02-05 13:35
Thanks for the update @dsulli99 . I'll close the issue since I have not been able to reproduce this.

**Closed by philippd** 2015-02-05 13:35 UTC
